const actionTypes = {
  GET_PATIENT: "GET_PATIENT",
  GET_PRESCRIPTION: "GET_PRESCRIPTION",
  GET_PRESCRIPTION_DETAIL: "GET_PRESCRIPTION_DETAIL",
  GET_INVOICEINPATIENT: "GET_INVOICEINPATIENT"
}

export default actionTypes;