const actionTypes = {
  GET_PATIENT: "GET_PATIENT",
  GET_PRESCRIPTION: "GET_PRESCRIPTION",
  GET_PRESCRIPTION_DETAIL: "GET_PRESCRIPTION_DETAIL",
  GET_INVOICEINPATIENT: "GET_INVOICEINPATIENT",
  GET_PATIENT_DETAIL: "GET_PATIENT_DETAIL",
  GET_LIST_PRESCRIPTION: "GET_LIST_PRESCRIPTION"
}

export default actionTypes;