export const InvoiceInPatient= [
  
  { Title: "Trạng thái", Name: "stt" },
  { Title: "Cho phép in lại", Name: "allow_re_print_hos_con" },
  { Title: "Số tiền", Name: "amount" },
  { Title: "URL BHBL", Name: "bhbl_url" },
  { Title: "BHYT", Name: "bhyt" },
  { Title: "Tên thu ngân", Name: "cashier_name" },
  { Title: "Ngày nhập viện", Name: "check_in_date" },
  { Title: "Mã hồ sơ", Name: "check_in_out_hospital_record_id" },
  { Title: "Ngày xuất viện", Name: "check_out_date" },
  { Title: "Đã đóng", Name: "closed" },
  { Title: "Ngày tạo", Name: "created" },
  { Title: "Thời gian tạo", Name: "created_time" },
  { Title: "Đã xóa", Name: "deleted" },
  { Title: "Số tiền giảm", Name: "discount_amount" },
  { Title: "Khoa kết thúc", Name: "end_department" },
  { Title: "Mã khoa kết thúc", Name: "end_department_id" },
  { Title: "Loại tài khoản", Name: "enum_account_type" },
  { Title: "Loại khám", Name: "enum_examination_type" },
  { Title: "Loại hóa đơn", Name: "enum_invoice_type" },
  { Title: "Loại bệnh nhân", Name: "enum_patient_type" },
  { Title: "Hình thức thanh toán", Name: "enum_payment_type" },
  { Title: "Khoa ban đầu", Name: "first_department" },
  { Title: "Mã khoa ban đầu", Name: "first_department_id" },
  { Title: "Mã ICD10", Name: "icd10" },
  { Title: "ID ICD10", Name: "icd10_id" },
  { Title: "Số tiền BHYT chi trả", Name: "ins_paid_price" },
  { Title: "Phần trăm BHYT", Name: "ins_percentage" },
  { Title: "Số điện thoại giới thiệu", Name: "introduction_phone" },
  { Title: "Nội dung giới thiệu", Name: "introduction_text" },
  { Title: "Mã hóa đơn", Name: "invoice_code" },
  { Title: "Mã hóa đơn mới", Name: "new_invoice_code" },
  { Title: "Ghi chú", Name: "note" },
  { Title: "Mã bệnh nhân", Name: "patient_id" },
  { Title: "Số tiền bệnh nhân", Name: "patient_price" },
  { Title: "ID tài liệu thanh toán", Name: "pay_payment_account_document_id" },
  { Title: "ID tài khoản thanh toán", Name: "pay_payment_account_id" },
  { Title: "ID biên lai", Name: "pay_receipt_id" },
  { Title: "Số tiền hoàn trả", Name: "pay_return" },
  { Title: "Phải thu", Name: "phai_thu" },
  { Title: "Phải trả", Name: "phai_tra" },
  { Title: "In thông báo thanh toán", Name: "print_notice_payment" },
  { Title: "Thanh toán BHYT thực tế", Name: "real_ins_payment" },
  { Title: "Thanh toán dịch vụ thực tế", Name: "real_ser_payment" },
  { Title: "Mã hóa đơn hoàn trả", Name: "refund_invoice_code" },
  { Title: "Đã hoàn trả", Name: "returned" },
  { Title: "Số hợp đồng", Name: "so_hd" },
  { Title: "Số lưu trữ", Name: "so_luu_tru" },
  { Title: "Loại phẫu thuật", Name: "surgery_type" },
  { Title: "ID vé", Name: "ticket_id" },
  { Title: "Tổng dự kiến", Name: "total_foresee" },
  { Title: "Tổng tiền BHYT chi trả", Name: "total_ins_paid_price" },
  { Title: "Tổng tiền BHYT", Name: "total_ins_price" },
  { Title: "Tổng tiền", Name: "total_price" },
  { Title: "Tổng thanh toán thực tế", Name: "total_real_payment" },
  { Title: "Tổng tiền dịch vụ", Name: "total_ser_price" },
  { Title: "ID điều trị", Name: "treatment_id" }
];
