// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerApi.Data;

#nullable disable

namespace ServerApi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerApi.Model.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAccount"));

                    b.Property<string>("CodeAccount")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("dataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("IdAccount");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ServerApi.Model.BoxChat", b =>
                {
                    b.Property<int>("IdBoxChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBoxChat"));

                    b.Property<string>("CodeBoxChat")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int>("IdFriend")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("ImageBox")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TitleBoxChat")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("dataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("IdBoxChat");

                    b.ToTable("BoxChats");
                });

            modelBuilder.Entity("ServerApi.Model.BoxChatGroup", b =>
                {
                    b.Property<int>("IdBoxChatGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBoxChatGroup"));

                    b.Property<string>("CodeBoxChatGroup")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageBoxGroup")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TitleBoxChatGroup")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("dataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("IdBoxChatGroup");

                    b.ToTable("BoxChatGroups");
                });

            modelBuilder.Entity("ServerApi.Model.InfoAccount", b =>
                {
                    b.Property<int>("IdInfoAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInfoAccount"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodeInfoAccount")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int>("IdAccount")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("char(9)");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("IdInfoAccount");

                    b.ToTable("InfoAccounts");
                });

            modelBuilder.Entity("ServerApi.Model.ListUserOfBoxChat", b =>
                {
                    b.Property<int>("IdListUserOfBoxChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdListUserOfBoxChat"));

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int>("IdBoxChatGroup")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("IdListUserOfBoxChat");

                    b.ToTable("listUserOfBoxChats");
                });

            modelBuilder.Entity("ServerApi.Model.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessage"));

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int>("IdBoxChat")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.Property<int>("type_message")
                        .HasColumnType("integer");

                    b.HasKey("IdMessage");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ServerApi.Model.MessageGroup", b =>
                {
                    b.Property<int>("IdMessageGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessageGroup"));

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int>("IdBoxChatGroup")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("MessagesGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("IdMessageGroup");

                    b.ToTable("MessageGroups");
                });

            modelBuilder.Entity("ServerApi.Model.Perrmisson", b =>
                {
                    b.Property<int>("IdPermisson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermisson"));

                    b.Property<string>("CodePermisson")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int>("IdRoles")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDetele")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("boolean");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("IdPermisson");

                    b.ToTable("Perrmissons");
                });

            modelBuilder.Entity("ServerApi.Model.Roles", b =>
                {
                    b.Property<int>("IdRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRoles"));

                    b.Property<string>("CodeRoles")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("IdRoles");

                    b.ToTable("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
